name: CI
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: index.html
          DESTINATION: index.html
          TOOLCHAIN: respec
          GH_PAGES_BRANCH: gh-pages
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: content/index.html
          DESTINATION: content/index.html
          TOOLCHAIN: respec
          GH_PAGES_BRANCH: gh-pages
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: help/index.html
          DESTINATION: help/index.html
          TOOLCHAIN: respec
          GH_PAGES_BRANCH: gh-pages
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: tools/index.html
          DESTINATION: tools/index.html
          TOOLCHAIN: respec
          GH_PAGES_BRANCH: gh-pages
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: requirements/index.html
          DESTINATION: requirements/index.html
          TOOLCHAIN: respec
          GH_PAGES_BRANCH: gh-pages
