name: CI
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build and Validate
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 1
      matrix:
        include:
          - source: index.html
            destination: index.html
          - source: content/index.html
            destination: content/index.html
          - source: help/index.html
            destination: help/index.html
          - source: tools/index.html
            destination: tools/index.html
          - source: requirements/index.html
            destination: requirements/index.html
    steps:
      - uses: actions/checkout@v2
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
          GH_PAGES_BRANCH: gh-pages
          DESTINATION: ${{ matrix.destination }}
